import React, { useState, useEffect, useCallback } from 'react';
import { useTranslation } from 'react-i18next';

import { api } from '../lib/api';
import { scopeCaption, scopedPermissions } from '../lib/permissions';
import { useAuth } from '../context/auth';
import Icon from '../components/Icon';
import Pagination from '../components/Pagination';
import { usePagination } from '../lib/pagination';
import ConfirmDialog from '../components/ConfirmDialog';

const EMPTY_FORM = { name: '', description: '', permissions: [] };

export default function RolesPanel() {
  const { t } = useTranslation();
  const { can } = useAuth();

  const [roles, setRoles] = useState([]);
  // Permission catalog, grouped by model — generated by the server registry,
  // so a newly added model appears here with no frontend change.
  const [catalog, setCatalog] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const [confirming, setConfirming] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [kindFilter, setKindFilter] = useState('all');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingRole, setEditingRole] = useState(null);
  const [formData, setFormData] = useState(EMPTY_FORM);
  const [formError, setFormError] = useState('');

  const loadData = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const [rolesRes, permsRes] = await Promise.all([
        api('/api/roles'),
        api('/api/permissions'),
      ]);
      setRoles(rolesRes.roles);
      setCatalog(permsRes.models);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const handleOpenCreateModal = () => {
    setEditingRole(null);
    setFormData(EMPTY_FORM);
    setFormError('');
    setIsModalOpen(true);
  };

  const handleOpenEditModal = (role) => {
    setEditingRole(role);
    setFormData({
      name: role.name,
      description: role.description || '',
      permissions: [...role.permissions],
    });
    setFormError('');
    setIsModalOpen(true);
  };

  const togglePermission = (permission) => {
    setFormData((prev) => ({
      ...prev,
      permissions: prev.permissions.includes(permission)
        ? prev.permissions.filter((p) => p !== permission)
        : [...prev.permissions, permission],
    }));
  };

  const toggleModel = (entry) => {
    const hasAll = entry.permissions.every((p) => formData.permissions.includes(p));
    setFormData((prev) => ({
      ...prev,
      permissions: hasAll
        ? prev.permissions.filter((p) => !entry.permissions.includes(p))
        : [...new Set([...prev.permissions, ...entry.permissions])],
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setFormError('');

    try {
      await api(
        editingRole ? `/api/roles/${editingRole.id}` : '/api/roles',
        { method: editingRole ? 'PUT' : 'POST', body: formData }
      );
      setIsModalOpen(false);
      loadData();
    } catch (err) {
      setFormError(err.message);
    }
  };

  const handleDeleteRole = async (role) => {
    try {
      await api(`/api/roles/${role.id}`, { method: 'DELETE' });
      loadData();
    } catch (err) {
      setError(err.message);
    }
  };

  const askToDeleteRole = (role) => setConfirming({
    message: t('panels.roles.confirmDelete', { name: role.name }),
    run: () => handleDeleteRole(role),
  });

  const filteredRoles = roles.filter((role) => {
    const haystack = `${role.name} ${role.description || ''}`.toLowerCase();
    const matchesSearch = haystack.includes(searchTerm.trim().toLowerCase());
    /*
     * The system role is the one kept in sync with the permission catalogue and
     * cannot be deleted, so it behaves differently from the rest and is worth
     * being able to set aside.
     */
    const matchesKind = kindFilter === 'all'
      || (kindFilter === 'system' ? role.is_system : !role.is_system);
    return matchesSearch && matchesKind;
  });

  const page = usePagination(filteredRoles);

  if (loading) return <div className="loading-state">{t('panels.roles.loading')}</div>;
  if (error) {
    return (
      <div className="error-banner">
        <Icon name="error" filled /> {error}
      </div>
    );
  }

  return (
    <div>
      <div className="panel-toolbar">
        <div className="metrics-row">
          <div className="metric-box">
            <div className="metric-value">{roles.length}</div>
            <div className="metric-label">{t('panels.roles.title')}</div>
          </div>
          <div className="metric-box">
            <div className="metric-value">{catalog.length}</div>
            <div className="metric-label">{t('panels.roles.registeredModels')}</div>
          </div>
          <div className="metric-box">
            <div className="metric-value">
              {catalog.reduce((total, entry) => total + entry.permissions.length, 0)}
            </div>
            <div className="metric-label">{t('panels.roles.availablePermissions')}</div>
          </div>
        </div>
        {can('roles:create') && (
          <button onClick={handleOpenCreateModal} className="btn btn-primary">
            <Icon name="add" /> {t('panels.roles.add')}
          </button>
        )}
      </div>

      <p className="subtitle">{t('panels.roles.explainer')}</p>

      <div className="filters-bar">
        <label className="search-field">
          <Icon name="search" />
          <input
            type="text"
            placeholder={t('panels.roles.searchPlaceholder')}
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
        </label>
        <select
          value={kindFilter}
          onChange={(e) => setKindFilter(e.target.value)}
          className="role-select"
        >
          <option value="all">{t('panels.roles.allKinds')}</option>
          <option value="system">{t('panels.roles.kindSystem')}</option>
          <option value="custom">{t('panels.roles.kindCustom')}</option>
        </select>
      </div>

      <div className="table-responsive">
        <table className="users-table">
          <thead>
            <tr>
              <th>{t('common.id')}</th>
              <th>{t('panels.roles.role')}</th>
              <th>{t('panels.roles.granted')}</th>
              <th>{t('panels.actions')}</th>
            </tr>
          </thead>
          <tbody>
            {filteredRoles.length === 0 ? (
              <tr>
                <td colSpan="4" className="empty-state">
                  {t(roles.length === 0 ? 'panels.roles.none' : 'panels.roles.noMatches')}
                </td>
              </tr>
            ) : (
              page.visible.map((role) => (
                <tr key={role.id}>
                  <td>#{role.id}</td>
                  <td>
                    <div className="user-name">
                      <span className={`role-pill role-${role.name}`}>{role.name}</span>
                      {role.is_system && <span className="badge system-badge">{t('panels.roles.system')}</span>}
                    </div>
                    <div className="user-email">{role.description}</div>
                  </td>
                  <td>
                    <div className="permissions-list">
                      {role.permissions.length > 0 ? (
                        role.permissions.map((perm) => (
                          <span key={perm} className="perm-tag">{perm}</span>
                        ))
                      ) : (
                        <span className="no-perm">{t('common.none')}</span>
                      )}
                    </div>
                  </td>
                  <td>
                    <div className="actions-group">
                      {can('roles:update') && (
                        <button onClick={() => handleOpenEditModal(role)} className="btn-action edit">
                          <Icon name="edit" /> {t('common.edit')}
                        </button>
                      )}
                      {can('roles:delete') && !role.is_system && (
                        <button onClick={() => askToDeleteRole(role)} className="btn-action delete">
                          <Icon name="delete" /> {t('common.delete')}
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <Pagination state={page} />

      {isModalOpen && (
        <div className="modal-overlay">
          <div className="modal-content">
            <div className="modal-header">
              <h3>
                {editingRole
                  ? t('panels.roles.editTitle', { id: editingRole.id })
                  : t('panels.roles.createTitle')}
              </h3>
              <button onClick={() => setIsModalOpen(false)} className="close-btn" aria-label={t('common.close')}><Icon name="close" /></button>
            </div>

            {formError && <div className="modal-error">{formError}</div>}

            <form onSubmit={handleSubmit}>
              {editingRole?.is_system && (
                <div className="modal-note">{t('panels.roles.systemNote')}</div>
              )}

              <div className="form-group">
                <label>{t('panels.roles.name')}</label>
                <input
                  type="text"
                  required
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  placeholder={t('panels.roles.namePlaceholder')}
                />
              </div>

              <div className="form-group">
                <label>{t('panels.roles.description')}</label>
                <input
                  type="text"
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  placeholder={t('panels.roles.descriptionPlaceholder')}
                />
              </div>

              <div className="form-group">
                <label>{t('panels.roles.permissions')}</label>
                <div className="permission-matrix">
                  {catalog.map((entry) => {
                    const allChecked = entry.permissions.every((p) =>
                      formData.permissions.includes(p)
                    );
                    return (
                      <div key={entry.model} className="matrix-row">
                        <div className="matrix-model">
                          <label className="checkbox-label">
                            <input
                              type="checkbox"
                              checked={allChecked}
                              onChange={() => toggleModel(entry)}
                            />
                            <strong>{t(`models.${entry.model}.label`, { defaultValue: entry.label })}</strong>
                          </label>
                        </div>
                        {/* One line per scope. Models nobody can own have only
                            the unscoped line, and it needs no caption. */}
                        {entry.scopes.map((scope) => (
                          <div key={scope} className="matrix-actions">
                            {scopeCaption(t, entry, scope) && (
                              <span className="scope-label">{scopeCaption(t, entry, scope)}</span>
                            )}
                            {scopedPermissions(entry, scope).map(({ action, permission }) => (
                              <label key={permission} className="checkbox-label">
                                <input
                                  type="checkbox"
                                  checked={formData.permissions.includes(permission)}
                                  onChange={() => togglePermission(permission)}
                                />
                                {t(`panels.action.${action}`)}
                              </label>
                            ))}
                          </div>
                        ))}
                      </div>
                    );
                  })}
                </div>
              </div>

              <div className="modal-footer">
                <button type="button" onClick={() => setIsModalOpen(false)} className="btn btn-secondary">
                  {t('common.cancel')}
                </button>
                <button type="submit" className="btn btn-primary">
                  {editingRole ? t('common.saveChanges') : t('panels.roles.createTitle')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {confirming && (
        <ConfirmDialog
          title={t('panels.roles.confirmDeleteTitle')}
          message={confirming.message}
          confirmLabel={t('common.delete')}
          destructive
          onCancel={() => setConfirming(null)}
          onConfirm={async () => {
            await confirming.run();
            setConfirming(null);
          }}
        />
      )}
    </div>
  );
}
