import fs from 'node:fs/promises';
import { createReadStream, constants as fsConstants } from 'node:fs';
import path from 'node:path';

/**
 * Objects as files on this machine's disk.
 *
 * The counterpart to the in-memory database driver: with no bucket configured
 * the app still boots and uploads still work. It is also what the tests run
 * against, which is the point — nothing in the suite needs a credential, a
 * network, or a bucket that somebody has to remember to empty.
 *
 * Not for production behind more than one instance: two servers would each
 * hold half the attachments, and a container's disk does not survive a
 * redeploy. That is what the S3 provider is for.
 */
export function createLocalFileProvider(directory) {
  const root = path.resolve(directory);

  /**
   * The path a key maps to, refusing anything that climbs out of the root.
   * Keys are generated by this server and never by a client, so this is a
   * belt-and-braces check rather than the only thing standing in the way.
   */
  const pathFor = (key) => {
    const resolved = path.resolve(root, key);
    if (resolved !== root && !resolved.startsWith(root + path.sep)) {
      throw new Error(`Object key escapes the storage directory: ${key}`);
    }
    return resolved;
  };

  return {
    name: 'local',

    /** Makes sure the directory exists and can be written to. */
    async check() {
      await fs.mkdir(root, { recursive: true });
      await fs.access(root, fsConstants.W_OK);
      return true;
    },

    async put(buffer, { key } = {}) {
      const target = pathFor(key);
      await fs.mkdir(path.dirname(target), { recursive: true });
      await fs.writeFile(target, buffer);
      return { providerId: key, size: buffer.length };
    },

    async get(providerId, { range } = {}) {
      const target = pathFor(providerId);

      let stat;
      try {
        stat = await fs.stat(target);
      } catch {
        // A row can outlive its bytes — a restored database, a wiped disk.
        // That is a miss, not a crash.
        return null;
      }

      const wanted = parseRange(range, stat.size);

      if (!wanted) {
        return {
          status: 200,
          body: createReadStream(target),
          size: stat.size,
          mime: null,
          headers: { 'accept-ranges': 'bytes' },
        };
      }

      return {
        status: 206,
        body: createReadStream(target, { start: wanted.start, end: wanted.end }),
        size: wanted.end - wanted.start + 1,
        mime: null,
        headers: {
          'accept-ranges': 'bytes',
          'content-range': `bytes ${wanted.start}-${wanted.end}/${stat.size}`,
        },
      };
    },

    async remove(providerId) {
      try {
        await fs.unlink(pathFor(providerId));
        return true;
      } catch (err) {
        // Already gone is the outcome asked for.
        if (err.code === 'ENOENT') return true;
        throw err;
      }
    },
  };
}

/** `bytes=start-end`, as far as a single range goes. Null when unusable. */
function parseRange(header, total) {
  const match = /^bytes=(\d*)-(\d*)$/.exec(String(header || '').trim());
  if (!match) return null;

  const [, rawStart, rawEnd] = match;
  if (rawStart === '' && rawEnd === '') return null;

  // `bytes=-500` means the last 500 bytes, not "everything up to 500".
  const start = rawStart === '' ? Math.max(0, total - Number(rawEnd)) : Number(rawStart);
  const end = rawStart === '' || rawEnd === ''
    ? total - 1
    : Math.min(total - 1, Number(rawEnd));

  if (start > end || start >= total) return null;
  return { start, end };
}
