import { randomUUID } from 'node:crypto';

import { modelList } from './models/index.js';
import { query } from './index.js';

/**
 * Every column of every table, as table -> Set(column).
 *
 * One query rather than one per table, and the reason is latency rather than
 * tidiness: boot cost here is round trips, not rows. A managed database is
 * routinely 150ms away, so the difference between one read of the catalogue and
 * a dozen is the difference between a boot and a timeout — see syncSchema.
 */
async function columnsByTable() {
  const res = await query(
    `SELECT table_name, column_name FROM information_schema.columns
      WHERE table_schema = current_schema()`
  );

  const byTable = new Map();
  for (const row of res.rows) {
    if (!byTable.has(row.table_name)) byTable.set(row.table_name, new Set());
    byTable.get(row.table_name).add(row.column_name);
  }
  return byTable;
}

/** The indexes that already exist, by name. */
async function existingIndexes() {
  const res = await query(
    `SELECT indexname FROM pg_indexes WHERE schemaname = current_schema()`
  );
  return new Set(res.rows.map((row) => row.indexname));
}

/**
 * The name a CREATE INDEX statement is about to claim.
 *
 * Parsed rather than passed alongside because the statements are generated by
 * Model#indexes to a fixed shape. It is only ever an optimisation — every
 * statement is IF NOT EXISTS regardless, so a name this fails to read costs one
 * round trip rather than a wrong answer.
 */
function indexName(statement) {
  return statement.match(/IF NOT EXISTS (\S+)/)?.[1] ?? null;
}

/**
 * Brings a table predating the uuid column up to date. Values are generated by
 * the application rather than by gen_random_uuid(), so this works whatever the
 * server version and matches what new rows get.
 */
async function ensureUuidColumn(model, present, log) {
  if (present.has('uuid')) return;

  await query(`ALTER TABLE ${model.table} ADD COLUMN uuid UUID`);

  const rows = await query(`SELECT id FROM ${model.table} WHERE uuid IS NULL`);
  for (const row of rows.rows) {
    await query(`UPDATE ${model.table} SET uuid = $1 WHERE id = $2`, [randomUUID(), row.id]);
  }

  // Only constrain it once every row satisfies the constraint.
  await query(`ALTER TABLE ${model.table} ALTER COLUMN uuid SET NOT NULL`);
  await query(
    `ALTER TABLE ${model.table} ADD CONSTRAINT ${model.table}_uuid_key UNIQUE (uuid)`
  );
  log.info(`Added ${model.table}.uuid (${rows.rowCount} existing row(s) backfilled).`);
}

/**
 * Adds the scope column to a permission side table that predates own-scoped
 * permissions. Everything already stored was unscoped, which is exactly what
 * `any` means, so the default backfills it correctly.
 */
async function migratePermissionScope(model, columns, log) {
  for (const relation of Object.values(model.relations)) {
    if (relation.kind !== 'permissionSet') continue;
    if (columns.get(relation.through)?.has('scope')) continue;

    await query(`ALTER TABLE ${relation.through} ADD COLUMN scope VARCHAR(8) NOT NULL DEFAULT 'any'`);
    // The scope is part of what makes a grant unique: the same action may be
    // held at both scopes at once.
    await query(`ALTER TABLE ${relation.through} DROP CONSTRAINT IF EXISTS ${relation.through}_pkey`);
    await query(
      `ALTER TABLE ${relation.through} ADD PRIMARY KEY (${relation.localKey}, model, action, scope)`
    );
    log.info(`Added ${relation.through}.scope (existing grants kept their "any" scope).`);
  }
}

/**
 * Adds columns declared on a model but missing from an existing table, so
 * adding a field to a model definition reaches a database that already exists.
 *
 * New columns are always nullable, even when the field is required: an
 * existing table may hold rows with no value for them, and a NOT NULL without
 * a default would fail outright. Backfill, then tighten by hand if you want
 * the constraint enforced in the database as well as in the model layer.
 */
async function syncColumns(model, present, log) {
  await ensureUuidColumn(model, present, log);

  for (const field of Object.values(model.fields)) {
    if (present.has(field.column)) continue;

    await query(`ALTER TABLE ${model.table} ADD COLUMN ${model.addColumnDefinition(field)}`);

    if (field.unique) {
      await query(
        `ALTER TABLE ${model.table} ADD CONSTRAINT ${model.table}_${field.column}_key UNIQUE (${field.column})`
      );
    }

    log.info(
      `Added ${model.table}.${field.column}` +
      (field.required ? ' (nullable — declared required, backfill existing rows)' : '')
    );
  }
}

/**
 * Every foreign key in the schema, as `table.column -> { name, rule }`.
 *
 * One query, for the same reason columnsByTable is one: boot cost here is round
 * trips rather than rows.
 */
async function foreignKeysByColumn() {
  const res = await query(
    `SELECT tc.table_name, kcu.column_name, tc.constraint_name, rc.delete_rule
       FROM information_schema.table_constraints tc
       JOIN information_schema.key_column_usage kcu
         ON kcu.constraint_name = tc.constraint_name
        AND kcu.constraint_schema = tc.constraint_schema
       JOIN information_schema.referential_constraints rc
         ON rc.constraint_name = tc.constraint_name
        AND rc.constraint_schema = tc.constraint_schema
      WHERE tc.constraint_type = 'FOREIGN KEY'
        AND tc.table_schema = current_schema()`
  );

  return new Map(res.rows.map((row) => [
    `${row.table_name}.${row.column_name}`,
    { name: row.constraint_name, rule: row.delete_rule },
  ]));
}

/** The columns that currently accept null, as `table.column`. */
async function nullableColumns() {
  const res = await query(
    `SELECT table_name, column_name FROM information_schema.columns
      WHERE table_schema = current_schema() AND is_nullable = 'YES'`
  );
  return new Set(res.rows.map((row) => `${row.table_name}.${row.column_name}`));
}

/**
 * Brings an existing foreign key into line with what its model now declares.
 *
 * `ON DELETE` is not a detail: it decides what a delete takes with it, and the
 * database enforces it without any model hook running. `files.owner_id` said
 * CASCADE, which meant deleting an account destroyed every file it had ever
 * uploaded — rows removed by Postgres itself, so nothing ran to remove the
 * objects behind them, and the bucket kept them forever. It says SET NULL now,
 * and this is what carries that to a database created before it did.
 *
 * Postgres cannot alter a constraint's action in place, so it is dropped and
 * re-added under the same name. Only ever on a real difference: a schema
 * already matching its models does nothing here.
 *
 * NOT NULL is only ever *relaxed*, never applied. Tightening could fail against
 * rows that are already there — the same reason syncColumns adds new columns
 * nullable whatever the model says.
 */
async function syncReferenceRules(model, foreignKeys, nullable, log) {
  for (const field of Object.values(model.fields)) {
    if (field.type !== 'reference') continue;

    const at = `${model.table}.${field.column}`;

    if (!field.required && !nullable.has(at)) {
      await query(`ALTER TABLE ${model.table} ALTER COLUMN ${field.column} DROP NOT NULL`);
      log.info(`${at} is no longer required; dropped its NOT NULL.`);
    }

    const existing = foreignKeys.get(at);
    if (!existing || existing.rule === field.onDelete) continue;

    await query(`ALTER TABLE ${model.table} DROP CONSTRAINT ${existing.name}`);
    await query(
      `ALTER TABLE ${model.table} ADD CONSTRAINT ${existing.name}
         FOREIGN KEY (${field.column}) REFERENCES ${model.targetTable(field.target)}(id)
         ON DELETE ${field.onDelete}`
    );
    log.info(`${at} is now ON DELETE ${field.onDelete} (was ${existing.rule}).`);
  }
}

/**
 * Adds a payload column declared on a relation but missing from a link table
 * that already exists.
 *
 * The counterpart of syncColumns for side tables. Always nullable: the rows are
 * already there and have no value for it, which is also the right starting
 * state — a membership nobody has read from yet has read nothing.
 */
async function syncRelationColumns(model, columns, log) {
  for (const relation of Object.values(model.relations)) {
    if (relation.kind !== 'manyToMany' || !relation.carriesPayload) continue;

    const present = columns.get(relation.through) ?? new Set();
    for (const field of Object.values(relation.columns)) {
      if (present.has(field.column)) continue;
      await query(`ALTER TABLE ${relation.through} ADD COLUMN ${field.column} ${field.sql}`);
      log.info(`Added ${relation.through}.${field.column}.`);
    }
  }
}

/**
 * Moves read position out of its own table and onto the membership it belongs
 * to.
 *
 * How far somebody has read in a group is a fact about their membership, not
 * about either end of it — so it lives on user_group_users, where the pair is
 * already the primary key and where leaving takes it away without anybody
 * having to remember to. user_group_reads was a table keeping that in step by
 * hand, and could drift.
 *
 * Only ever acts while the old table is still there, so a boot after the first
 * one does nothing. The join is the whole migration: a marker for a pair that
 * is no longer a membership has nowhere to land and is dropped with the table,
 * which is the correct outcome — it described a group the person had left.
 */
async function migrateReadMarkers(columns, log) {
  if (!columns.has('user_group_reads')) return;

  log.info('Moving read markers onto the memberships they belong to.');

  const moved = await query(`
    UPDATE user_group_users AS link
       SET last_read_at = marker.last_read_at
      FROM user_group_reads AS marker
     WHERE marker.group_id = link.user_group_id
       AND marker.user_id = link.user_id
       AND link.last_read_at IS NULL
  `);

  await query('DROP TABLE user_group_reads');
  log.info(
    `Dropped user_group_reads (${moved.rowCount} marker(s) moved onto user_group_users).`
  );
}

/**
 * Moves data off the pre-refactor schema, where a user carried a `role` string
 * and its own `permissions` array. Idempotent: it only acts while the legacy
 * columns are still present.
 */
async function migrateLegacyUserColumns(present, log) {
  if (present.has('role')) {
    log.info('Migrating legacy users.role values into roles + user_roles.');

    // Create any role named by existing data but missing from the seed.
    await query(`
      INSERT INTO roles (name, description, is_system)
      SELECT DISTINCT u.role, 'Imported from legacy users.role', false
      FROM users u
      WHERE u.role IS NOT NULL AND u.role <> ''
      ON CONFLICT (name) DO NOTHING
    `);

    await query(`
      INSERT INTO user_roles (user_id, role_id)
      SELECT u.id, r.id FROM users u JOIN roles r ON r.name = u.role
      ON CONFLICT DO NOTHING
    `);

    await query('ALTER TABLE users DROP COLUMN role');
    log.info('Dropped users.role (fully represented by user_roles now).');
  }

  if (present.has('name')) {
    // A single `name` became first_name + last_name. Split on the first space;
    // a single-word name becomes the first name with the last name left blank.
    log.info('Splitting legacy users.name into first_name / last_name.');
    await query(`
      UPDATE users SET
        first_name = COALESCE(NULLIF(split_part(name, ' ', 1), ''), name),
        last_name  = NULLIF(substr(name, strpos(name, ' ') + 1), name)
      WHERE name IS NOT NULL AND (first_name IS NULL OR last_name IS NULL)
    `);
    await query('ALTER TABLE users DROP COLUMN name');
    log.info('Dropped users.name.');
  }

  if (present.has('permissions')) {
    // Per-user permissions have no home in the new model, and the legacy
    // vocabulary (users:write, admin:access) does not map cleanly onto
    // <model>:<action>. Keep the data rather than destroy it, but take it out
    // of the way so inserts no longer need to satisfy NOT NULL.
    await query('ALTER TABLE users RENAME COLUMN permissions TO legacy_permissions');
    await query('ALTER TABLE users ALTER COLUMN legacy_permissions DROP NOT NULL');
    log.warn(
      'Per-user permissions are no longer used. The old values were preserved ' +
      'in users.legacy_permissions — drop that column once you have reviewed it.'
    );
  }
}

/**
 * Runs every model's schema(), then migrates legacy data.
 *
 * The registry hands models over in dependency order, so a table is always
 * created before anything that references it — a model's own table and side
 * tables can therefore be created together.
 */
export async function syncSchema(log) {
  // Pass one: every table, in the order the registry hands the models over, so
  // a table is always created before anything that references it.
  for (const model of modelList) {
    for (const statement of model.schema()) {
      await query(statement);
    }
  }

  // Then the catalogue, once, now that everything a fresh database needs exists.
  // Reading it here rather than per model is what keeps the boot inside its
  // budget on a database that is not local — see columnsByTable.
  const columns = await columnsByTable();
  const indexes = await existingIndexes();
  const foreignKeys = await foreignKeysByColumn();
  const nullable = await nullableColumns();

  // Pass two: reconcile what the tables hold against what the models declare.
  for (const model of modelList) {
    // Creating a table is a no-op when it already exists, so fields added to a
    // model definition later are reconciled here instead.
    await syncColumns(model, columns.get(model.table) ?? new Set(), log);
    await syncRelationColumns(model, columns, log);
    await syncReferenceRules(model, foreignKeys, nullable, log);
    await migratePermissionScope(model, columns, log);

    // Last for this model, so a column syncColumns has only just added is there
    // to be indexed. Skipping the ones that exist is again about round trips:
    // IF NOT EXISTS makes the statement safe, not free, and on a steady-state
    // boot every one of them is a wasted trip.
    for (const statement of model.indexes()) {
      const name = indexName(statement);
      if (name && indexes.has(name)) continue;
      await query(statement);
    }
  }

  // After the pass above, so the column the markers move into exists.
  await migrateReadMarkers(columns, log);
  await migrateLegacyUserColumns(columns.get('users') ?? new Set(), log);
  // The finished state goes to stdout like the other boot lines; the migration
  // steps above stay on `log`, where their structure and timing are worth having.
  console.log(`✅ Schema ready for models: ${modelList.map((m) => m.name).join(', ')}.`);
}
